# Copyright 2025 ExpA_sys
"""Actions described as Model Context Protocol tool definitions.

MCP is the shape chosen for this form for one reason: it is the format an instruction-tuned model
has already seen thousands of times as "here is a tool you may call". Encoding an action in a
format the encoder already understands costs nothing and avoids inventing a private notation.

**The template here is the single source of truth, and it has no copy on disk.** There used to be a
a generated `mcp_prompt.md` next to the schemas, regenerated by a script and kept honest by a gate that
diffed it against a fresh one. Both were dropped on 2026-08-26: the encoder builds its prompts
from `action_config` at call time and never read that file, so it was a second copy of something
already derivable, and the gate existed only because the copy existed. To read what the encoder
actually reads, print it:

    python experiments/tools/show_action_descriptions.py --env alfworld --text mcp --full
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from agent_system.policies.dyad.models.action_descriptions import CATALOGUE_TEMPLATE

if TYPE_CHECKING:  # pragma: no cover
    from agent_system.policies.dyad.models.action_descriptions import ActionDoc

# Place identity and description after the JSON so causal hidden states can attend to the definition.
# Omit benchmark names; environment context comes from the shared catalogue.
PROMPT_TEMPLATE = """\
You are reading the definition of "{name}" that an agent can take in this environment.

{body}

{label}: {name}
Description: {description}

Understand this "{name}": what it does, what input it needs, and when an agent would choose it.\
"""

# Closed-value rows describe their full value set independently of any referencing tool.
VALUE_TEMPLATE = """\
You are reading the definition of "{name}" that an agent can take in this environment.

{body}

Understand this "{name}": what it does, what input it needs, and when an agent would choose it.\
"""

# Tool labels only; closed values use VALUE_TEMPLATE.
LABELS = {"tool": "Action"}


def _json(doc: "ActionDoc") -> str:
    return json.dumps(doc.mcp, indent=2, ensure_ascii=False, sort_keys=False)


def _value_choices(doc: "ActionDoc") -> str:
    """Render the full owning value set for a closed-value row without truncation."""
    return json.dumps(list(doc.value_choices), ensure_ascii=False)


def format_action(doc: "ActionDoc") -> str:
    if doc.kind == "value":
        return VALUE_TEMPLATE.format(name=doc.name, body=_value_choices(doc))
    return PROMPT_TEMPLATE.format(
        name=doc.name,
        body=_json(doc),
        label=LABELS.get(doc.kind, "Action"),
        description=doc.description,
    )


def format_catalogue(docs: list["ActionDoc"]) -> str:
    """Render a catalogue of tool definitions in head-row order.

    Only tool rows become entries. Parameter and value rows would duplicate their
    owning definitions; synthetic kind labels are not part of MCP.
    """
    entries = [f"- `{doc.name}`:\n{_json(doc)}" for doc in docs if doc.kind == "tool"]
    return CATALOGUE_TEMPLATE.format(catalogue_body="\n".join(entries))
